name: Build and Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  release-client:
    uses: AlienXAXS/StarRupture-Plugin-SDK/.github/workflows/plugin-release.yml@main
    with:
      plugin_name: WaveOptimiser_Plugin
      solution_file: WaveOptimiser_Plugin.sln
      variant: Client
    secrets: inherit

  release-server:
    uses: AlienXAXS/StarRupture-Plugin-SDK/.github/workflows/plugin-release.yml@main
    with:
      plugin_name: WaveOptimiser_Plugin
      solution_file: WaveOptimiser_Plugin.sln
      variant: Server
    secrets: inherit
